# Generated by Django 4.1.7 on 2023-04-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
