# Generated by Django 4.1.7 on 2023-04-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_homepage_banner_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
    ]
